site_name: COMP423 Course Notes
theme:
  name: material
  palette: 
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details